from django.urls import path, include
from .views import BookList, BookViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # list only endpoint
    path('books/', BookList.as_view(), name='book-list'),

    # CRUD endpoint generated by router
    path('', include(router.urls))
]